#Propiedades que se van a leer basandose en ficheros de propiedades en YAML

guru:
  jms:
    name: JMS username
    password: JMS password
    topicurl: JMS topic url

---

#Propiedades basadas en diferentes perfiles
spring:
  profiles: de

guru:
  jms:
    name: JMS username in German!!!